import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./custom-components/Navbar";
import Footer from "./custom-components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-geist-popins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Add the weights you need
});

export const metadata: Metadata = {
  title: "Cyberprobe-x",
  description: "Generated by Hacfy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
