import type { Metadata } from "next"
import { Geist, Geist_Mono, Poppins, Inter } from "next/font/google"
import "./globals.css"
import Navbar from "./custom-components/Navbar"
import Footer from "./custom-components/Footer"
import LanguageSwitcher from "@/components/languge-switch"
import ChatBot from "./custom-components/ChatBot"
import Script from "next/script"

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] })
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] })
const poppins = Poppins({ variable: "--font-geist-popins", subsets: ["latin"], weight: ["300", "400", "500", "600", "700"] })
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "CyberProbeX",
  description: "Generated by CyberProbeX",
  icons: { icon: "/CPX.png" },
  keywords: [
    "cyberprobex",
    "cyberprobe",
  ],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics Script */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-QYWPHG78P1"
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-QYWPHG78P1');
            `
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} ${inter.className} antialiased`}>
        <Navbar />
        <LanguageSwitcher />
        <ChatBot />
        {children}
        <Footer />
      </body>
    </html>
  )
}
